In [ ]:
import numpy as np
import pandas as pd

u1 = [0, 1, 0, 1, 1]
u2 = [0, 1, 0, 0, 0]
u3 = [0, 1, 1, 0, 0]
u4 = [0, 1, 1, 1, 0]

train_data = [u1, u2, u3, u4]
n_users = len(train_data)
# convert list to pandas dataframe

train_df = pd.DataFrame(train_data, columns=["u1", "u2", "u3", "u4", "u5"])
train_df = np.array(train_df)

In [9]:

# 1. Item interaction counts - vectorized calculation
print("Computing item interaction counts...")
item_counts_vec = np.array(train_df.sum(axis=0)).flatten()  # Sum across users

Computing item interaction counts...


In [10]:
print("Item interaction counts (vectorized):")
print(item_counts_vec)

Item interaction counts (vectorized):
[0 4 2 2 1]


In [11]:
# Create a matrix where each row is the item counts
item_counts = np.tile(item_counts_vec, (n_users, 1))

In [12]:
print("Item interaction counts (matrix):")
print(item_counts)

Item interaction counts (matrix):
[[0 4 2 2 1]
 [0 4 2 2 1]
 [0 4 2 2 1]
 [0 4 2 2 1]]


In [13]:
# 2. Calculate co-interaction counts using fully vectorized operations
print("Computing user similarity matrix...")
# Convert to CSR for efficient operations
train_csr = train_df.tocsr()
train_csr

Computing user similarity matrix...


AttributeError: 'DataFrame' object has no attribute 'tocsr'